#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

exec="../../../bin/prepareCase.sh"

if [ -x "$exec" ]
then
    . $exec
else
    echo "The file $WAVES_DIR/bin/prepareCase.sh is not executable."
    echo "Make the file executable before continuing."
    echo
    echo "Exiting tutorial case."
    exit 1
fi

# Set application name
application="waveFoam"

# Create mesh
runApplication blockMesh

# Create internal wall (v2306: faceSet utility replaced by topoSet;
# createBaffles now dictionary-driven via system/createBafflesDict)
runApplication topoSet
runApplication setsToZones -noFlipMap
runApplication createBaffles -overwrite

# Set wave parameters
runApplication setWaveParameters

# Set wave field
runApplication setWaveField

# Run application in parallel (system/decomposeParDict: 8 ranks, scotch)
runApplication decomposePar
runParallel $application
runApplication reconstructPar


